:concurrency: 5
:timeout: 25
:verbose: false

:queues:
  - default
  - mailers
  - active_storage_analysis
  - active_storage_purge

development:
  :concurrency: 2

staging:
  :concurrency: 3

production:
  :concurrency: 10
