:concurrency: <%= ENV.fetch('SIDEKIQ_CONCURRENCY', 5) %>
:timeout: 25
:verbose: false
:max_retries: 3
:retry_interval: 60

:queues:
  - [critical, 3]
  - [default, 2]
  - [mailers, 1]
  - [active_storage_analysis, 1]
  - [active_storage_purge, 1]

development:
  :concurrency: 2
  :verbose: true

staging:
  :concurrency: 3
  :verbose: false

production:
  :concurrency: <%= ENV.fetch('SIDEKIQ_CONCURRENCY', 10) %>
  :verbose: false
  :logfile: log/sidekiq.log
  :pidfile: tmp/pids/sidekiq.pid
  :daemon: true
